package my.prosjektarbeid;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Petter
 */
public class Register extends javax.swing.JFrame {
    ArrayList<String> users = new ArrayList<String>();
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textfield_username = new javax.swing.JTextField();
        textfield_pw1 = new javax.swing.JPasswordField();
        textfield_pw2 = new javax.swing.JPasswordField();
        button_makeuser = new javax.swing.JButton();
        button_forgottenpw = new javax.swing.JButton();
        textfield_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lag ny bruker", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setText("Brukernavn:");

        jLabel2.setText("Passord:");

        jLabel3.setText("Gjenta Passord:");

        button_makeuser.setText("Opprett bruker");
        button_makeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_makeuserActionPerformed(evt);
            }
        });

        button_forgottenpw.setText("Glemt passord?");

        textfield_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_emailActionPerformed(evt);
            }
        });

        jLabel4.setText("E-post:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_makeuser)
                        .addGap(28, 28, 28)
                        .addComponent(button_forgottenpw))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfield_email)
                            .addComponent(textfield_pw2)
                            .addComponent(textfield_username)
                            .addComponent(textfield_pw1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfield_pw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textfield_pw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_makeuser)
                    .addComponent(button_forgottenpw))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_emailActionPerformed
    /**
     * 
     * @param username Denne tar inn brukernavnet som brukeren har skrevet inn, og sjekker om navnet finnes i en liste med navn på alle brukerne. Hvis 
     * navnet allerde er tilegnet en bruker, legges det til i feedback at denne brukeren allerde finnes.
     * @param email Denne parameteren tar inn emailen og sjekker om epostadressen inneholder en alfakrøll. 
     * @return Denne funksjonen tar to parameterne og sjekker de to siste, som er passordfeltene, uten å ta de inn. Den har en string variabel som kalles feedback,
     * og her legges det til kommentarer etter hvert som testene utføres. Hvis for eksempel navnet allerede fines i databasen, legger man til: "Denne brukeren finnes allerede."
     * i feedback variabelen. På slutten av funksjonen sjekker man om feedback er tom, hvis den er det legger man inn teksten: "Gratulerer".
     */
    private String check_input(String username, String email) {
        String feedback = "";
        if (users.contains(username)) {
            feedback += "Denne brukeren finnes allerede.";        
        }
        
        if (!Arrays.equals(textfield_pw1.getPassword(), textfield_pw2.getPassword())) {
            feedback += "Du har ikke skrevet inn to like passord!";
        }
        
        
        if(email.indexOf("@") == -1) {
            feedback += "Du har ingen alfakrøll i epostadressen din!";
        }
        if (feedback =="") {
            feedback += "Gratulerer!";
        }
        return feedback;
    }
    private void button_makeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_makeuserActionPerformed
        
        System.out.println(check_input(textfield_username.getText(), textfield_email.getText()));
    }//GEN-LAST:event_button_makeuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String token = args[0];
        System.out.println(token);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
        
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_forgottenpw;
    private javax.swing.JButton button_makeuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textfield_email;
    private javax.swing.JPasswordField textfield_pw1;
    private javax.swing.JPasswordField textfield_pw2;
    private javax.swing.JTextField textfield_username;
    // End of variables declaration//GEN-END:variables
}
